### ISSUE TITLE
Investigate removing liquidity issue reported by users

### ISSUE THREAD

**Issue by ilia-andr** [LimeChain/HeliSwap-frontend#360]
Some users cannot remove liquidity. The stated that clearing cookies/Cache fixes it. 

Error which the users get
{ "name": "StatusError", "status": "CONTRACT_REVERT_EXECUTED", "transactionId": "0.0.1328945@1665612366.443899894", "message": "receipt for transaction 0.0.1328945@1665612366.443899894 contained error status CONTRACT_REVERT_EXECUTED" }

**Comment by RAMTO** [comment]
@ilia-andr Fixed
